name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Run build
        run: yarn build --prod

      - name: Run lint
        run: yarn lint
